workflows:
  android-build:
    name: Android Build
    environment:
      java: 17
    scripts:
      - chmod +x ./gradlew     # ✅ Isso dá permissão de execução
      - ./gradlew clean build  # 🧪 Agora ele vai conseguir rodar
    artifacts:
      - app/build/outputs/**/*.apk
