workflows:
  android-build:
    name: Android Build
    environment:
      java: 17
      android:
        sdk: 34
    scripts:
      - ./gradlew clean build
    artifacts:
      - app/build/outputs/**/*.apk

